config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    edit: '',
    update: ''
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue nil
  
  root 'subscriptions#index'

  resource :users, only: [:show, :edit, :update]

  resource :subscriptions 
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    unless user.nil?
      authorize_user(user)
    else
        #Permissions for guests
        can :index, Home
    end
  end

  def authotize_user user
    can :read, User
    
    can [:update, :edit], User do |other_user|
      user.id == other_user.id
    end

  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/career.rb
class Career < ActiveRecord::Base

  #
  # Fields
  #

  #name:string

  #
  # Validations
  #

  validates :name, presence: true

  #
  # Relations
  #

  has_many :users
  has_many :subjects

end

app/models/course.rb
class Course < ActiveRecord::Base

  #
  # Fields
  #

  #code:string
  #period:string

  #
  # Validations
  #

  validates :code, presence: true
  validates :period, presence: true
  validates :professor, presence: true
  validates :subject, presence: true
  validates :office, presence: true

  #
  # Relations
  #

  belongs_to :professor
  belongs_to :subject
  belongs_to :office
  has_many :solicitudes_to_leave, class_name: "Solicitude", foreign_key: "origin_course_id"
  has_many :solicitudes_to_transfer, class_name: "Solicitude", foreign_key: "wanted_course_id"

  #
  # Class Methods
  #

  def self.periods period
    periods = {morning: "mañana", evening: "tarde", night: "noche"}
    periods[period]
  end

end

app/models/office.rb
class Office < ActiveRecord::Base

  #
  # Fields
  #

  #name:string

  #
  # Validations
  #

  validates :name, presence: true

  #
  # Relations
  #

  belongs_to :regional
  has_many :courses

end

app/models/professor.rb
class Professor < ActiveRecord::Base

  #
  # Fields
  #

  #first_name:string
  #last_name:string

  #
  # Validations
  #

  validates :first_name, presence: true
  validates :last_name, presence: true

  #
  # Relations
  #

  has_many :courses

end

app/models/regional.rb
class Regional < ActiveRecord::Base
  
  #
  # Fields
  #

  #name:string
  #short_name:string

  #
  # Validations
  #

  validates :name, presence: true
  validates :short_name, presence: true

  #
  # Relations
  #

  has_many :offices

end

app/models/solicitude.rb
class Solicitude < ActiveRecord::Base

  #
  # Fields
  #

  #solicitant_comments:text
  #applicant_comments:text

  #
  # Validations
  #

  validates :solicitant, presence: true
  validates :applicant, presence: true
  validates :origin_course, presence: true
  validates :wanted_course, presence: true

  #
  # Relations
  #  

  belongs_to :solicitant, class_name: "User"
  belongs_to :applicant, class_name: "User"
  belongs_to :origin_course, class_name: "Course"
  belongs_to :wanted_course, class_name: "Course"

end

app/models/subject.rb
class Subject < ActiveRecord::Base

  #
  # Fields
  #

  #name:string
  #short_name:string
  #kind:string

  #
  # Validations
  #

  validates :name, presence: true
  validates :kind, presence: true
  validates :career, presence: true, unless: :general?

  #
  # Relations
  #

  belongs_to :career
  has_many :courses

  #
  # Class Methods
  #

  def self.kinds(kind)
    subject_kinds = {general: "homogeneas", systems: "sistemas", mechanic: "mecanica", electric: "electronica", civil: "civil", naval: "naval", quimic: "quimica"}
    subject_kinds[kind]
  end

  #
  # Instance Methods
  #

  def general?
    self.kind == self.class.kinds(:general)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #
  # Fields
  #

  #email:string
  #password:string
  #first_name:string
  #last_name:string
  #birth_date:date

  #
  # Validations
  #

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :career, presence: true

  #
  # Relations
  #

  belongs_to :career
  has_many :solicitudes, foreign_key: "solicitant_id" #These are the ones the user created
  has_many :applications, class_name: "Solicitude", foreign_key: "applicant_id" #These are the ones the user applied to

  #
  # CanCanCan
  #
  
  delegate :can?, :cannot?, :authorize!, to: :ability

  #
  # Instance Methods
  #

  def ability
    @ability ||= Ability.new(self)
  end

  def full_name
    #Move to a decorator?
    "#{first_name} #{last_name}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def index
    
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    
  end

  def edit

  end

  def update

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CambiosCursos
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    = content_tag :meta, "", name: "viewport", content: "width=devise-width, initial-scale=1"
  %body
    = render "shared/header"
    - if flash[:alert]
      .alert{data: {alert: flash[:alert]}}
    - if flash[:error]
      .error{data: {error: flash[:error]}}
    - if flash[:notice]
      .notice{data: {notice: flash[:notice]}}
    = yield
    = render "shared/footer"
    = javascript_include_tag 'application'
    = yield(:scripts)

app/views/shared/_filters.html.haml
#collapse-search.panel-collapse.collapse
  .panel-body
    .row
      .col-md-3
        .input-group
          .full-width
            %label
              regional
          .full-width
            %input
        .input-group
          .full-width
            %label
              materia
          .full-width
            %input
          
      .col-md-3
        .input-group
          .full-width
            %label
              sede
          .full-width
            %input
        .input-group
          .full-width
            %label 
              curso origen 
          .full-widthorigen
            %input
      .col-md-3
        .input-group
          .full-width
            %label
              especialidad
          .full-width
            %input
        .input-group
          .full-width
            %label 
              curso destino
          .full-widthdestino
            %input

      .col-md-3
        .input-group
          .full-width
            %label
              profesor
          .full-width
            %input
        .input-group
          .full-width
            %label 
              turno
          .full-width
            %input

    .form-actions.text-center
      %button.btn.btn-primary
        Filtrar

app/views/shared/_header.html.haml
%nav{class: "navbar navbar-default"}
  .container-fluid
    .navbar-header
    %ul.nav.navbar-nav
      %li
        = link_to root_path do
          = image_tag "logo.png", size: "50x50"
    %ul.nav.navbar-nav.pull-right.devise-links
      - if current_user.blank?
        %li
          = link_to t(".sign_up"), new_user_registration_path
        %li
          = link_to t(".sign_in"), new_user_session_path
      - else
        %li
          = link_to t(".edit_profile"), edit_users_path
        %li
          = link_to t(".new_subscription"), new_subscriptions_path
        %li
          = link_to t(".sign_out"), destroy_user_session_path, method: :delete

app/views/shared/_subscriptions_table.html.haml
%table.table.table-striped.table-responsive
  %thead
    %tr
      %th
        regional
      %th
        especialidad
      %th
        curso origen
      %th
        curso destino
  %tbody
    %tr
      %td
        FRBA
      %td
        sistemas
      %td
        k3078
      %td
        k2056

app/views/subscriptions/index.html.haml
.container
  .panel-group
    .panel.panel-default
      .panel-heading
        .row
          .col-md-1.text-left
            %a{href: "#collapse-search", data: {toggle: "collapse"}}
              Filtros

      = render "shared/filters"

  = render "shared/subscriptions_table"